version: '3'

services:
  consul_server_01:
    image: consul:1.15.4
    container_name: consul_server_01
    hostname: cs01
    ports:
      - 8500:8500        
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server01:/etc/consul.d

  consul_server_02:
    image: consul:1.15.4
    container_name: consul_server_02
    hostname: cs02  
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server02:/etc/consul.d

  consul_server_03:
    image: consul:1.15.4
    container_name: consul_server_03
    hostname: cs03  
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server03:/etc/consul.d

  consul_client_01:
    image: consul:1.15.4
    container_name: consul_client_01
    hostname: cc01  
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul01:/etc/consul.d
  
  consul_client_02:
    image: consul:1.15.4
    container_name: consul_client_02
    hostname: cc02  
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul02:/etc/consul.d

  consul_client_03:
    image: consul:1.15.4
    container_name: consul_client_03
    hostname: cc03  
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul03:/etc/consul.d
